language: node_js
node_js:
  - 11
sudo: required
services:
  - docker

before_install:
  - docker build -t jlfly12/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run jlfly12/multi-client npm test -- --coverage

after_success:
  - docker build -t jlfly12/multi-client ./client
  - docker build -t jlfly12/multi-nginx ./nginx
  - docker build -t jlfly12/multi-server ./server
  - docker build -t jlfly12/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jlfly12/multi-client
  - docker push jlfly12/multi-nginx
  - docker push jlfly12/multi-server
  - docker push jlfly12/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: fib_calculator
  env: FibCalculator-env
  bucket_name: elasticbeanstalk-us-east-1-390784745265
  bucket_path: fib_calculator
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
